
Promise.reject(345).catch(err=>{
    console.log(err);
})